name: CI/CD robotframework

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repository
        uses: actions/checkout@v4
      - name: installer Python
        uses: actions/setup-python@v4 
        with: 
          python-version: "3.10"
      - name: Installer les dependences 
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Créer le dossier des résultats (si besoin)
        run: mkdir -p resultats_de_test/

      - name: lancer le test de robotframework
        run: robot -d ./taharframe.robot 
      - name: telecharger les resultats 
        uses:  actions/upload-artifact@v4
        with: 
            name: afficher les resultats
            path: resultats_de_test/
