name: CI Test Robotframework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # ou pypy3.10 selon tes besoins

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install geckodriver
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y firefox  
    - name: Install Geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/


    - name: Run amazonframe.robot
      run: robot amazonframe.robot

    - name: Run facebook.robot
      run: robot facebook.robot
