name: Run Robot Framework Tests

on:
  push:
    branches: main
  pull_request:
    branches: main 

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: | 
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install -r requirements.txt
    - name: Istall mozilla  
      run: |
       sudo apt-get update
       sudo apt-get install -y firefox
       GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
       wget -q https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VERSION}/geckodriver-v${GECKO_VERSION}-linux64.tar.gz
       tar -xzf geckodriver-v${GECKO_VERSION}-linux64.tar.gz
       chmod +x geckodriver
       sudo mv geckodriver /usr/local/bin

    - name: Run facebook.robot test
      run: robot facebook.robot

    - name: Run amazon.robot test
      run: robot amazon.robot
